version: "3.8"

services:
  # Install Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831"
      - "16686:16686"
      - "14268"
      - "14250"

  # Install Collector
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger

  # Install Elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  # Install Fluentd
  fluentd:
    build: ./fluentd
    ports:
      - "12201:12201"
    volumes:
      - source: ./fluentd
        target: /fluentd/etc
        type: bind
    depends_on:
      - elasticsearch

  # Install Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Install Redpanda
  redpanda:
    container_name: redpanda
    image: vectorized/redpanda
    hostname: redpanda
    ports:
      - "9092:9092"