receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/elastic:
    endpoint: 127.0.0.1:9200
    insecure: true

  logging:

  jaeger:
    endpoint: 127.0.0.1:14250
    insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - jaeger
        - otlp/elastic